imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    secret: "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation:
        enable_annotations: true
    templating:
        engines:
            - 'twig'
    default_locale: "%locale%"
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        handler_id:  ~
    fragments: ~
    http_method_override: true

# Twig Configuration
twig:
    debug: "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_sqlite
        memory: false
        path: %kernel.root_dir%/../db/newsletter.sqlite
        charset: UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host: "%mailer_host%"
    username: "%mailer_user%"
    password: "%mailer_password%"
    spool:
        type: memory

# newsletter config
xsolve_newsletter:
    send_key: %newsletter_send_key%
    tasks_per_time: %newsletter_tasks_per_time%
    from_mail: %newsletter_from_mail%
    from_name: %newsletter_from_name%
